invalid_credentials = "Invalid email address or password."
not_found = "The requested resource was not found."
no_json_content = "No JSON content found or incorrect mime type set."
parent_id_not_found = "The declared parentId was not found."
list_id_not_found = "The declared listId was not found."
